import os
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def run_tests():
    result = subprocess.run(
        ["python", "bot/tester/test_projects.py"],
        cwd=ROOT,
        capture_output=True,
        text=True
    )

    return result.stdout, result.returncode


def create_issue(title, body):
    command = [
        "gh",
        "issue",
        "create",
        "--title",
        title,
        "--body",
        body,
        "--label",
        "zybot"
    ]

    result = subprocess.run(
        command,
        cwd=ROOT,
        capture_output=True,
        text=True
    )

    if result.returncode == 0:
        print("✅ Issue created:")
        print(result.stdout)
    else:
        print("⚠️ Could not create issue:")
        print(result.stderr)


def main():
    print("=" * 55)
    print("🧬 ZYBOT — REPORTER")
    print("=" * 55)

    output, return_code = run_tests()

    print(output)

    if return_code != 0:
        print("\n⚠️ Tester encountered an execution problem.")
        return

    failed_lines = []

    for line in output.splitlines():
        if line.startswith("❌"):
            failed_lines.append(line)

    if not failed_lines:
        print("\n🟢 Zybot found no failed projects.")
        return

    print(f"\n🔎 Problems detected: {len(failed_lines)}")

    body = """## Zybot automated report

Zybot's Tester detected the following project(s) requiring attention:

"""

    for line in failed_lines:
        body += f"- {line}\n"

    body += """

### Source

This issue was automatically generated by Zybot.

Zybot does not modify `main` automatically.

Review the affected project and close this issue when resolved.
"""

    create_issue(
        "🧬 Zybot detected project problems",
        body
    )


if __name__ == "__main__":
    main()
